name: Procesar Encuestas Python

on:
  workflow_dispatch: # Permite ejecución manual desde API

permissions:
  contents: write # Permiso para guardar los excel en el repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl xlsxwriter gspread oauth2client

      - name: Ejecutar Script
        run: python procesar.py

      - name: Guardar y Subir Cambios (Commit)
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add *.xlsx
          # Solo hace commit si hay cambios
          git commit -m "Reportes generados automáticamente" || echo "Sin cambios para subir"
          git push
